{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
---
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rathole-operator
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: rathole-operator
    app.kubernetes.io/component: manager
    {{- include "rathole-operator.selector-labels" . | nindent 4 }}
    {{- include "rathole-operator.created-meta" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "rathole-operator.selector-labels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{ include "rathole-operator.selector-labels" . | nindent 8 }}
    spec:
      affinity:
        {{ .Values.affinity | toYaml | nindent 8 }}
      nodeSelector:
        {{ .Values.nodeSelector | toYaml | nindent 8 }}
      securityContext:
        runAsNonRoot: true
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 10
