# permissions for end users to view ratholeclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ratholeclient-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rathole-operator
    app.kubernetes.io/part-of: rathole-operator
    app.kubernetes.io/managed-by: kustomize
  name: ratholeclient-viewer-role
rules:
- apiGroups:
  - rathole.superclass.io
  resources:
  - ratholeclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rathole.superclass.io
  resources:
  - ratholeclients/status
  verbs:
  - get
