# permissions for end users to edit ratholeservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ratholeservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rathole-operator
    app.kubernetes.io/part-of: rathole-operator
    app.kubernetes.io/managed-by: kustomize
  name: ratholeservice-editor-role
rules:
- apiGroups:
  - rathole.superclass.io
  resources:
  - ratholeservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rathole.superclass.io
  resources:
  - ratholeservices/status
  verbs:
  - get
