apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: rathole-operator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rathole-operator
    app.kubernetes.io/part-of: rathole-operator
    app.kubernetes.io/managed-by: kustomize
  name: rathole-operator
  namespace: system
