name: Docker Build and Push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract tags
        id: extract_tags
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          IMAGE_TAGS=$TAG
          PREFIX_TAG=${TAG%%-*}
          if [ "$TAG" != "$PREFIX_TAG" ]; then
            IMAGE_TAGS="$IMAGE_TAGS,$PREFIX_TAG"
          fi
          echo "tags=$IMAGE_TAGS" >> $GITHUB_ENV

      - name: Build and push Docker images
        run: |
          TAGS=$(echo ${{ env.tags }} | tr "," "\n")
          for TAG in $TAGS; do
            docker buildx build --platform linux/amd64,linux/arm64 --push -t crmin/rathole-operator:$TAG .
          done
